### ISSUE TITLE
Create R project & tidy folder structure

### ISSUE THREAD

**Issue by simon-tarr** [laurajanegraham/geb_r2#7]
Either of us to do this.

**Comment by laurajanegraham** [comment]
I have this as an R project on my computer - I tend to put those bits in `.gitignore`. 

Agreed needs a tidy folder structure.

**Comment by simon-tarr** [comment]
I'm not sure as to the best practise surrounding .rproj files on GitHub...this is my first proper collaboration via Git.

**Comment by laurajanegraham** [comment]
I *think* that it's best not to put those files on Github. I'm basing this on the fact that if you click "create gitignore" when setting up an rproject, it automatically adds in the rproj etc. files to be ignored. I may be wrong though.

**Comment by simon-tarr** [comment]
Yeah I just Googled it - seems to be a matter of some debate in some quarters.
So I guess we clone the repo and create our own project locally?

**Comment by laurajanegraham** [comment]
Yup, I reckon so.

**Comment by simon-tarr** [comment]
Okay no problem.

I've been syncing my most recent project's RProj file to enable me to work across my laptop and desktop. I Guess though when several people are involved it could get messy.

**Comment by simon-tarr** [comment]
Done!
